name: Deploy to InfinityFree

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build (if needed)
        run: npm run build

      - name: Upload to FTP
        uses: actions/upload-artifact@v3
        with:
          name: deploy-files
          path: .

      - name: Download the Artifact (for example purposes)
        uses: actions/download-artifact@v3
        with:
          name: deploy-files

      - name: Deploy to FTP
        run: |
          lftp -c "set ftp:passive-mode 1; open $FTP_HOST; login $FTP_USERNAME $FTP_PASSWORD; cd $FTP_PATH; mirror ./deploy-files/ . ; close; quit"
        env:
          FTP_HOST: ftp.infinityfree.com
          FTP_USERNAME: if0_38575681
          FTP_PASSWORD: Eviltwin123
          FTP_PATH: ftpupload.net


