name: Deploy to InfinityFree

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to FTP
        run: |
          sudo apt-get update && sudo apt-get install -y lftp
          lftp -e "
            set ftp:passive-mode on;
            open $FTP_HOST;
            user $FTP_USERNAME $FTP_PASSWORD;
            mirror --reverse --delete --verbose ./ $FTP_PATH;
            bye
          "
        env:
         FTP_HOST: ftp.infinityfree.com
          FTP_USERNAME: if0_38575681
          FTP_PASSWORD: Eviltwin123
          FTP_PATH: ftpupload.net


